### ISSUE TITLE
未実装のコメントアウト

### ISSUE THREAD

**Issue by nissy-code** [c0a2103528/ProjExD#6]
未実装だったら, その部分をコメントアウトしておいてもいいかもしれないです.
''' もしくは """ で囲うなどしたほうがわかるし, 見やすいかもしれないです.

https://github.com/c0a2103528/ProjExD/blob/a179b73da5fa7e5c0bda67d0815af6be2de4f32b/ex03/maze.py#L17-L28

**Comment by c0a2103528** [comment]
他の方からも同様のご指摘をいただき、修正いたしました。ご指摘ありがとうございます。
